// RootIB: RB-20260307022444-F7DC88DA
import axios from "axios";
import { getPages, savePages } from "./pageStore.js";

/**
 * Generate a description and narration script for a single page.
 *
 * TODO: Replace the stub below with a real LLM call, e.g.:
 *   const completion = await openai.chat.completions.create({ ... });
 *
 * @param {{ path: string, content: string }} param0
 * @returns {{ summary: string, enhanced_description: string, script: string }}
 */
async function generateDescriptionFromContent({ path, content }) {
  // Stub — replace with your actual LLM call
  const summary = `This page (${path}) is part of your protocol repo.`;
  const enhanced = `This page, located at ${path}, plays a specific role in your system. ` +
    `It likely defines a tool, protocol, or documentation artifact. ` +
    `In the full implementation, this text would be a rich, human-friendly explanation ` +
    `generated by an LLM based on the file contents.`;
  const script = `Welcome. This page is called ${path}. It is part of your protocol repository. ` +
    `In the full system, I would explain exactly what this page does, who should use it, ` +
    `and how it fits into the larger protocol.`;
  return { summary, enhanced_description: enhanced, script };
}

async function fetchFileContent(raw_url) {
  try {
    const res = await axios.get(raw_url);
    return res.data;
  } catch (err) {
    throw new Error(`Failed to fetch content from ${raw_url}: ${err.message}`);
  }
}

export async function generateDescriptionsForAll() {
  const pages = await getPages();
  const updated = [];

  for (const page of pages) {
    try {
      const content = await fetchFileContent(page.raw_url);
      const { summary, enhanced_description, script } =
        await generateDescriptionFromContent({ path: page.path, content });

      updated.push({
        ...page,
        summary,
        enhanced_description,
        script,
        last_described_at: new Date().toISOString()
      });
    } catch (err) {
      console.error(`[descriptionGenerator] Skipping ${page.path}: ${err.message}`);
      updated.push(page);
    }
  }

  await savePages(updated);
  return updated;
}
