#!/usr/bin/env node

/**
 * Automated Onboarding Script
 * 
 * This script automates the initial setup process:
 * 1. Generates a unique UNIVERSE_KEY (UUID v4)
 * 2. Creates .env file with core required variables
 * 3. Sets appropriate file permissions (600 for security)
 * 4. Validates the setup
 * 
 * Usage: npm run onboard
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// ANSI color codes for terminal output
const colors = {
    reset: '\x1b[0m',
    bright: '\x1b[1m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    blue: '\x1b[34m',
    red: '\x1b[31m',
    cyan: '\x1b[36m',
};

function log(message, color = 'reset') {
    console.log(`${colors[color]}${message}${colors.reset}`);
}

function generateUUID() {
    // Generate UUID v4
    return crypto.randomUUID();
}

function createEnvFile() {
    const envPath = path.join(process.cwd(), '.env');
    
    // Check if .env already exists
    if (fs.existsSync(envPath)) {
        log('⚠️  .env file already exists!', 'yellow');
        const readline = require('readline').createInterface({
            input: process.stdin,
            output: process.stdout
        });
        
        return new Promise((resolve) => {
            readline.question('Do you want to overwrite it? (y/N): ', (answer) => {
                readline.close();
                if (answer.toLowerCase() !== 'y') {
                    log('❌ Onboarding cancelled. Existing .env file preserved.', 'yellow');
                    process.exit(0);
                }
                resolve();
            });
        });
    }
    return Promise.resolve();
}

async function main() {
    log('\n╔════════════════════════════════════════════════════════════╗', 'cyan');
    log('║     🚀 Consciousness Revolution - Automated Onboarding     ║', 'cyan');
    log('╚════════════════════════════════════════════════════════════╝\n', 'cyan');
    
    try {
        // Step 1: Check for existing .env
        await createEnvFile();
        
        // Step 2: Generate UNIVERSE_KEY
        log('🔑 Generating unique UNIVERSE_KEY...', 'blue');
        const universeKey = generateUUID();
        log(`   Generated: ${universeKey}`, 'green');
        
        // Step 3: Create .env content
        log('\n📝 Creating .env file with core variables...', 'blue');
        const envContent = `# Environment Configuration
# Auto-generated by npm run onboard
# Generated: ${new Date().toISOString()}

# Universe Key - Unique identifier for system access
UNIVERSE_KEY=${universeKey}

# Node Environment - Set to 'development' for local work, 'production' for deployment
NODE_ENV=development

# Application Port - Port number for the local development server
PORT=3000

# ============================================================================
# Additional Configuration (Optional)
# ============================================================================
# For additional API keys and configuration options, see .env.example
# You can add any required API keys below as needed for your development work
`;
        
        const envPath = path.join(process.cwd(), '.env');
        fs.writeFileSync(envPath, envContent);
        log('   ✅ .env file created successfully', 'green');
        
        // Step 4: Set file permissions to 600 (read/write for owner only)
        log('\n🔒 Setting secure file permissions...', 'blue');
        try {
            fs.chmodSync(envPath, 0o600);
            log('   ✅ Permissions set to 600 (owner read/write only)', 'green');
        } catch (error) {
            log('   ⚠️  Could not set permissions (may require manual chmod 600 .env)', 'yellow');
        }
        
        // Step 5: Add .env to .gitignore if not already there
        log('\n🛡️  Ensuring .env is in .gitignore...', 'blue');
        const gitignorePath = path.join(process.cwd(), '.gitignore');
        if (fs.existsSync(gitignorePath)) {
            let gitignoreContent = fs.readFileSync(gitignorePath, 'utf8');
            if (!gitignoreContent.includes('.env')) {
                gitignoreContent += '\n# Environment variables\n.env\n';
                fs.writeFileSync(gitignorePath, gitignoreContent);
                log('   ✅ Added .env to .gitignore', 'green');
            } else {
                log('   ✓  .env already in .gitignore', 'green');
            }
        } else {
            log('   ⚠️  No .gitignore found (create one to protect .env)', 'yellow');
        }
        
        // Step 6: Summary
        log('\n╔════════════════════════════════════════════════════════════╗', 'green');
        log('║                  ✨ Onboarding Complete! ✨                 ║', 'green');
        log('╚════════════════════════════════════════════════════════════╝', 'green');
        
        log('\n📋 What was configured:', 'bright');
        log('   ✓  Generated unique UNIVERSE_KEY', 'green');
        log('   ✓  Created .env with 3 core variables', 'green');
        log('   ✓  Set secure file permissions', 'green');
        log('   ✓  Protected from version control', 'green');
        
        log('\n🎯 Next steps:', 'bright');
        log('   1. Run: npm run verify:setup', 'cyan');
        log('      (Validates your environment configuration)', 'cyan');
        log('   2. Run: npm run setup:git-hooks', 'cyan');
        log('      (Installs pre-commit secret scanning)', 'cyan');
        log('   3. Run: npm start', 'cyan');
        log('      (Start the application!)', 'cyan');
        
        log('\n💡 Tips:', 'bright');
        log('   - Add API keys to .env as needed for features you use', 'yellow');
        log('   - See .env.example for all available configuration options', 'yellow');
        log('   - Never commit .env to version control!', 'yellow');
        log('   - See DEVELOPER_ONBOARDING.md for role-specific guides\n', 'yellow');
        
    } catch (error) {
        log('\n❌ Onboarding failed:', 'red');
        log(`   ${error.message}`, 'red');
        process.exit(1);
    }
}

// Run the script
main();
